### ISSUE TITLE
Savage blow cleave doing more hits than it should 

### ISSUE THREAD

**Issue by VRR164** [VanillaPlusTeam/bug-tracker#107]
The savage blow cleave is doing phantom bonus hits when dual wielding. It doesn't do bonus hits with a 2 handed weapon or with only one 1 handed weapon.
On one target it hits 2 times 
On two targets it hits 6 times
On three targets it hits 12 times
On four targets it hits 20 times
On five targets it hits 30 times
On six targets it hits 42 times
On seven targets it hits 49 times

**Comment by Trymv1** [comment]
Confirming as I was a test dummy for a portion of this.

Seems as though the coding is crossed specifically on the DW portion to work like a Sweeping Strikes-Cleave interaction rather than a hit that happens to *just* cleave, like Rocky Bash.

Thus its hitting EVERY target once for every target beyond the first.
